"""Migration

Revision ID: fa0d2ec5d50c
Revises: 1394f1f86454
Create Date: 2021-09-01 22:54:19.172139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa0d2ec5d50c'
down_revision = '1394f1f86454'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('quantity', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'quantity')
    # ### end Alembic commands ###
